### ISSUE TITLE
Telegram uses AWS IPs too

### ISSUE THREAD

**Issue by KostyaEsmukov** [ojab/docker-dante-telegram#2]
I just want to bring to your attention that apparently Telegram has started using AWS IP addresses, which the current config doesn't allow, causing the client connection to hang when it tries to connect using Amazon IP.

**Comment by ojab** [comment]
hmm, any way to reproduce it? Works fine here with telegram-desktop.

I don't really know how we could handle it (opening proxy for all amazon IPs is not the wisest thing IMHO), any suggestions?

**Comment by ojab** [comment]
Works fine == I see only connections to Telegram IPs, for example `149.154.163.70:80` & `149.154.163.70:443` right now.
I assume that it can be reproduced somehow if Telegram IPs are be blocked (right now they're not blocked yet here), will try that later.

**Comment by ojab** [comment]
welp, AWS IPs
```
52.58.0.0/15 
18.196.0.0/15
18.194.0.0/15
35.156.0.0/14
```
have been banned by rkn too :/

**Comment by KostyaEsmukov** [comment]
Yup, this is the world we live in now 🔥.

> hmm, any way to reproduce it?

To see the blocked attempts in the logs I had to add a blocking block at the end of the config:

    socks block {
        from: 0.0.0.0/0
        to: 0.0.0.0/0
        log: error connect
    }

> I don't really know how we could handle it (opening proxy for all amazon IPs is not the wisest thing IMHO), any suggestions?

I ended up removing restrictions on target subnets completely for the moment.

**Comment by ojab** [comment]
Pushed version with authentication support and banned Amazon/Google networks added (see README), hope it fixes this issue.

Feel free to reopen if your usecase still not covered.

**Comment by KostyaEsmukov** [comment]
Thanks. I don't use this project, I just liked the subnets restriction idea initially and once I saw the rejected Amazon IPs in the logs I decided to inform you. In the meantime I'd be better not restrict the subnets at all for now, considering the instability of the situation, but YMMV.

**Comment by ojab** [comment]
JFYI: `--build-arg all_networks=true` is added to allow `0.0.0.0/0`, so that usecase also should be covered now.
